linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - golint
    - gomnd
    - gosec
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - prealloc
    - scopelint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
