linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - depguard
    - exhaustruct
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - golint
    - gomnd
    - gosec
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - prealloc
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
