// Code generated by assets compiler. DO NOT EDIT.
	
package main

var (
	templates = map[string]string{
"/markdown.tmpl": "# Bibliography\n\n{{ range .Entries -}}\n* {{ .Formatted }}\n{{ end }}\n",
}
)