name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "7 11 * * 6"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Build
        run: go build
      - name: Test
        run: go test -net -cover -coverprofile=coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: 1.21.x
      - name: Configure Go Environment
        run: |
          echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
          echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Bootstrap
        run: make bootstrap
      - name: Lint
        run: make lint
      - name: Generate
        run: make generate
      - name: Mod Tidy
        run: go mod tidy
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
